# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-12-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaccount', models.CharField(max_length=20)),
                ('upassword', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('uage', models.IntegerField(default=0)),
                ('ugender', models.BooleanField(default=True)),
                ('uhobby', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
